name: Stale PR
on:
  workflow_dispatch:
  push:
jobs:
  stale-pr:
    name: Stale PR
    runs-on: ubuntu-latest
    steps:
      - run: gh search repos archived:false --topic=team-flex --owner=navikt --limit=200 --json "name" --jq ".[] | .name"
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
